# Generated by Django 5.1.4 on 2024-12-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system2', '0003_rename_timestamp_receivedmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
