# Generated by Django 5.1.4 on 2024-12-20 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system2', '0004_rename_created_at_receivedmessage_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='message_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], default='sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='receivedmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system2_received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
